import numpy as np
arr = np.arange(1, 21)
print("Array:")
print(arr)
print("\nShape:")
print(arr.shape)
print("\nMaximum Value:")
print(arr.max())
print("\nMinimum Value:")
print(arr.min())
print("\nMean:")
print(arr.mean())
print("\nStandard Deviation:")
print(arr.std())
matrix = arr.reshape(4, 5)
print("\n4x5 Matrix:")
print(matrix)
print("\nSecond Row:")
print(matrix[1])
print("\nThird Column:")
print(matrix[:, 2])
